### ISSUE TITLE
Documentation footer shows only "all right reserved", should also display "BSD"

### ISSUE THREAD

**Issue by ccouturi** [python-hospital/hospital#51]
@benoitbryon cette licence n'est pas une licence open source :

"Copyright (c) 2013-2014, Benoît Bryon.
All rights reserved."

**Comment by benoitbryon** [comment]
It is a BSD license: http://opensource.org/licenses/BSD-3-Clause

**Comment by ccouturi** [comment]
Alors il faut que tu y ajoutes :
(cf template http://opensource.org/licenses/BSD-3-Clause)
Sinon on peut pas l'utiliser.

Copyright (c) 2013-2014, Benoît Bryon.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

**Comment by benoitbryon** [comment]
I do not understand the issue.

https://github.com/python-hospital/hospital/blob/master/LICENSE does contain more than just "Copyright (c) 2013-2014, Benoît Bryon. All rights reserved."
Can you highlight what's wrong?

Or perhaps a truncated version of the license is displayed somewhere? Where?

**Comment by ccouturi** [comment]
I was mistaken. My bad, sorry.
(I only look at site footer)

**Comment by benoitbryon** [comment]
Reopening the issue. The "all rights reserved" mention is located in the documentation footer.
This footer could be improved with some "BSD" notice, and a link to the full license document.
