### ISSUE TITLE
Move internal tests outside hospital package, i.e. from hospital/tests to tests/

### ISSUE THREAD

**Issue by benoitbryon** [python-hospital/hospital#62]
Internal tests are not part of the API, i.e. they are not made to be inherited/reused, and (currently) we do not see an use case where they could be reused.
Thus, those internal tests are not really useful inside the distribution. Whereas they are useful in the project's repository.

This refactoring may be useful for #50 / #57 (currently discussing), because internal tests may have additional requirements:

> One thing I do not know how to manage is the "py.test" dependency. I mean, if you need to run py.test in your tests... then tests depend on py.test, and if tests are in hospital package, then hospital package depends on py.test...

With this refactoring, tests can have py.test as a requirement, even if hospital itself does not.

**Comment by ftobia** [comment]
Would it be helpful for me to pull this changeset into its own pull request? https://github.com/ftobia/hospital/commit/cb3905778cb7c1736fd02915e1491f96eaf4d030

**Comment by benoitbryon** [comment]
Wait a couple of hours (or days perhaps, but I try to do it asap): I'm reviewing your pull-request, and may do some changes directly, while I experiment py.test support. I may pull-request to your pull-request, or something like that, so that you are given an opportunity to review/comment before it is actually merged into master.

**Comment by ftobia** [comment]
:+1:

Let me know how I can help going forward.
