### ISSUE TITLE
hospital-cli always exits with successful exit code (0)

### ISSUE THREAD

**Issue by jamesmulcahy** [python-hospital/hospital#73]
It doesn't matter how many failures you get, hospital-cli always exits with a 0 exit code.  This makes it a fiddle to integrate into other systems.

**Comment by benoitbryon** [comment]
Marked the ticket as a bug, and moved it to "soon" release.

The expected behaviour is (correct me if I am wrong):
- `hospital-cli` returns exit code 0 if all healthchecks pass.
- `hospital-cli` returns exit code 1 if there is at least one error or failure.
